####
#### rebindings ####
####

# for quick reload of config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
set -g @fzf_pane_switch_bind-key 'C-Space'

# new window with name prompt
bind c command-prompt -p "window name:" "new-window -n '%%'"

# open splits in current path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# cycle windows
bind -n M-l next-window
bind -n M-h previous-window

####
#### options ###
####

set -g status-interval 1
set -g escape-time 0
set -g repeat-time 350
set -g display-time 1500
set -g history-limit 50000

# set focus events on for nvim
set -g focus-events on

# options for color ####
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",ghostty:Tc:Ms=\\E]52;%p1%s;%p2%s\\007"

# options for indexes for window/session creation ###
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on

####
#### improved copy mode ####
####

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind x kill-pane

#####
##### Display Popups ##### 
#####

# lazygit
bind y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

# new session
bind S command-prompt -p "session name:" "new-session -d -s '%%' \; switch-client -t '%%'"

# click session name in status-left to open session chooser
bind-key -n MouseDown1StatusLeft choose-tree -Zs

# scratchpad
bind g display-popup -E -w 80% -h 80% -d "#{pane_current_path}" "tmux new-session -A -s scratch"

#####
##### Display Menu ##### 
#####

bind d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  "config.fish"       z  "display-popup -E 'nvim ~/.config/fish/config.fish'" \
  ".tmux.conf"        t  "display-popup -E 'nvim ~/.config/tmux/tmux.conf'" \
  "Exit"              q  ""

#####
##### Bootstrap Plugins ##### 
#####

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'cengebretson/tmux-which-key'   ## C + k
set -g @plugin 'cengebretson/fzf-pane-switch.tmux'

####
#### Configure Themes ####
####

# Toggle between appearance.conf and appearance2.conf
bind T run-shell "~/.config/tmux/toggle_theme.sh" \; source-file ~/.config/tmux/tmux.conf \;

# load theme file which is a symlink
source-file ~/.config/tmux/appearance.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Override plugin defaults that can't be set before plugin init
set -g window-status-bell-style "none"
